<?php

namespace Modules\Appointment\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Appointment\Models\Medicine;

class MedicinesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $medicines = [
            [
                'name' => 'Paracetamol 500mg Tablets',
                'generic_name' => 'Paracetamol',
                'brand_name' => 'Panadol',
                'strength' => '500mg',
                'dosage_form' => 'tablet',
                'manufacturer' => 'GSK',
                'category' => 'analgesic',
                'formulae' => 'C8H9NO2',
                'indication' => 'Pain relief, fever reduction',
                'side_effects' => 'Rare: skin rash, blood disorders with prolonged use',
                'contraindication' => 'Severe liver disease, hypersensitivity to paracetamol',
                'drug_interactions' => 'Warfarin (increased anticoagulant effect), alcohol (increased hepatotoxicity)',
                'pregnancy_category' => 'A',
                'storage_conditions' => 'Store below 25°C in a dry place',
                'price' => 2.50,
                'url' => 'https://bnf.nice.org.uk/drugs/paracetamol/',
                'status' => true,
            ],
            [
                'name' => 'Amoxicillin 250mg Capsules',
                'generic_name' => 'Amoxicillin',
                'brand_name' => 'Amoxil',
                'strength' => '250mg',
                'dosage_form' => 'capsule',
                'manufacturer' => 'GSK',
                'category' => 'antibiotic',
                'formulae' => 'C16H19N3O5S',
                'indication' => 'Bacterial infections: respiratory tract, urinary tract, skin and soft tissue',
                'side_effects' => 'Nausea, vomiting, diarrhea, skin rash, allergic reactions',
                'contraindication' => 'Penicillin allergy, infectious mononucleosis',
                'drug_interactions' => 'Oral contraceptives (reduced efficacy), warfarin (increased bleeding risk)',
                'pregnancy_category' => 'B',
                'storage_conditions' => 'Store below 25°C in a dry place',
                'price' => 8.75,
                'url' => 'https://bnf.nice.org.uk/drugs/amoxicillin/',
                'status' => true,
            ],
            [
                'name' => 'Omeprazole 20mg Capsules',
                'generic_name' => 'Omeprazole',
                'brand_name' => 'Losec',
                'strength' => '20mg',
                'dosage_form' => 'capsule',
                'manufacturer' => 'AstraZeneca',
                'category' => 'antacid',
                'formulae' => 'C17H19N3O3S',
                'indication' => 'Gastroesophageal reflux disease, peptic ulcer disease, Zollinger-Ellison syndrome',
                'side_effects' => 'Headache, nausea, diarrhea, abdominal pain, constipation',
                'contraindication' => 'Hypersensitivity to omeprazole or other proton pump inhibitors',
                'drug_interactions' => 'Clopidogrel (reduced efficacy), warfarin (increased bleeding risk)',
                'pregnancy_category' => 'C',
                'storage_conditions' => 'Store below 25°C, protect from moisture',
                'price' => 12.30,
                'url' => 'https://bnf.nice.org.uk/drugs/omeprazole/',
                'status' => true,
            ],
            [
                'name' => 'Salbutamol 100mcg Inhaler',
                'generic_name' => 'Salbutamol',
                'brand_name' => 'Ventolin',
                'strength' => '100mcg per dose',
                'dosage_form' => 'inhaler',
                'manufacturer' => 'GSK',
                'category' => 'bronchodilator',
                'formulae' => 'C13H21NO3',
                'indication' => 'Asthma, chronic obstructive pulmonary disease (COPD)',
                'side_effects' => 'Tremor, headache, tachycardia, muscle cramps',
                'contraindication' => 'Hypersensitivity to salbutamol',
                'drug_interactions' => 'Beta-blockers (antagonistic effect), digoxin (increased risk of arrhythmias)',
                'pregnancy_category' => 'C',
                'storage_conditions' => 'Store below 30°C, do not freeze',
                'price' => 6.50,
                'url' => 'https://bnf.nice.org.uk/drugs/salbutamol/',
                'status' => true,
            ],
            [
                'name' => 'Metformin 500mg Tablets',
                'generic_name' => 'Metformin',
                'brand_name' => 'Glucophage',
                'strength' => '500mg',
                'dosage_form' => 'tablet',
                'manufacturer' => 'Merck',
                'category' => 'antidiabetic',
                'formulae' => 'C4H11N5',
                'indication' => 'Type 2 diabetes mellitus',
                'side_effects' => 'Nausea, vomiting, diarrhea, abdominal pain, metallic taste',
                'contraindication' => 'Severe renal impairment, metabolic acidosis, diabetic ketoacidosis',
                'drug_interactions' => 'Alcohol (increased risk of lactic acidosis), contrast media (increased risk of nephrotoxicity)',
                'pregnancy_category' => 'B',
                'storage_conditions' => 'Store below 25°C in a dry place',
                'price' => 4.20,
                'url' => 'https://bnf.nice.org.uk/drugs/metformin-hydrochloride/',
                'status' => true,
            ],
            [
                'name' => 'Cetirizine 10mg Tablets',
                'generic_name' => 'Cetirizine',
                'brand_name' => 'Zyrtec',
                'strength' => '10mg',
                'dosage_form' => 'tablet',
                'manufacturer' => 'UCB',
                'category' => 'antihistamine',
                'formulae' => 'C21H25ClN2O3',
                'indication' => 'Allergic rhinitis, chronic urticaria',
                'side_effects' => 'Drowsiness, dry mouth, fatigue, headache',
                'contraindication' => 'Severe renal impairment, hypersensitivity to cetirizine',
                'drug_interactions' => 'Alcohol (increased sedation), CNS depressants (additive sedation)',
                'pregnancy_category' => 'B',
                'storage_conditions' => 'Store below 25°C in a dry place',
                'price' => 3.80,
                'url' => 'https://bnf.nice.org.uk/drugs/cetirizine-hydrochloride/',
                'status' => true,
            ],
            [
                'name' => 'Ibuprofen 400mg Tablets',
                'generic_name' => 'Ibuprofen',
                'brand_name' => 'Nurofen',
                'strength' => '400mg',
                'dosage_form' => 'tablet',
                'manufacturer' => 'Reckitt Benckiser',
                'category' => 'analgesic',
                'formulae' => 'C13H18O2',
                'indication' => 'Pain relief, inflammation, fever reduction',
                'side_effects' => 'Nausea, dyspepsia, diarrhea, headache, dizziness',
                'contraindication' => 'Active peptic ulcer, severe heart failure, severe renal impairment',
                'drug_interactions' => 'Warfarin (increased bleeding risk), ACE inhibitors (reduced efficacy)',
                'pregnancy_category' => 'C',
                'storage_conditions' => 'Store below 25°C in a dry place',
                'price' => 5.60,
                'url' => 'https://bnf.nice.org.uk/drugs/ibuprofen/',
                'status' => true,
            ],
            [
                'name' => 'Simvastatin 20mg Tablets',
                'generic_name' => 'Simvastatin',
                'brand_name' => 'Zocor',
                'strength' => '20mg',
                'dosage_form' => 'tablet',
                'manufacturer' => 'MSD',
                'category' => 'statin',
                'formulae' => 'C25H38O5',
                'indication' => 'Hypercholesterolemia, cardiovascular disease prevention',
                'side_effects' => 'Muscle pain, headache, nausea, constipation, flatulence',
                'contraindication' => 'Active liver disease, pregnancy, breastfeeding',
                'drug_interactions' => 'Warfarin (increased bleeding risk), grapefruit juice (increased statin levels)',
                'pregnancy_category' => 'X',
                'storage_conditions' => 'Store below 25°C, protect from light',
                'price' => 7.90,
                'url' => 'https://bnf.nice.org.uk/drugs/simvastatin/',
                'status' => true,
            ]
        ];

        foreach ($medicines as $medicine) {
            Medicine::create($medicine);
        }
    }
}